swagger: '2.0'

info:
  title: Global Parameters
  description: Global Parameters Used by Several Calls
  version: "1.0.0"

paths: {}

parameters:
  pageSize:
    name: pageSize
    in: query
    description: Number of persons returned
    type: integer
    format: int32
    minimum: 0
    exclusiveMinimum: true
    maximum: 100
    exclusiveMaximum: false
    multipleOf: 10
    default: 20
  pageNumber:
    name: pageNumber
    in: query
    description: Page number
    type: integer
    default: 1
  acceptLanguage:
    name: Accept-Language
    description: |
     All API consumers MUST provide a string to show which languages they will accept, for example

     * en,en-US,fr;q=0.6
     * en
     * es

     If this app does not support a language listed here then English will be the default language
    type: string
    in: header
    required: true

